name: Go CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # or your preferred Go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v

      - name: Run linter
        run: |
         go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
         golangci-lint run ./...

  merge-to-main:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Merge to main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff ${{ github.ref_name }}
          git push origin main
