name: Go CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Install development tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint

      - name: Run security checks
        run: make security

      - name: Check formatting
        run: make fmt
