name: Setup Branch Protection

on:
  workflow_dispatch:  # Allow manual triggering
  repository_dispatch:  # Allow triggering via API
    types: [setup_protection]

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - name: Setup Branch Protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Define protection rules for main branch
            const protection = {
              required_status_checks: {
                strict: true,
                contexts: ['build-and-test']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1
              },
              restrictions: null
            };

            try {
              // Update branch protection
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch: 'main',
                ...protection
              });
              console.log('Successfully updated branch protection rules');
            } catch (error) {
              console.error('Error updating branch protection:', error);
              throw error;
            } 